// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Reflexxes.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <Reflexxes.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __RoboCompReflexxes__Reflexxes__setJointPosition_name = "setJointPosition";

const ::std::string __RoboCompReflexxes__Reflexxes__getStatePosition_name = "getStatePosition";

}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::RoboCompReflexxes::upCast(::IceProxy::RoboCompReflexxes::Reflexxes* p) { return p; }

void
::IceProxy::RoboCompReflexxes::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompReflexxes::Reflexxes>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompReflexxes::Reflexxes;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::RoboCompReflexxes::Reflexxes::setJointPosition(const ::RoboCompReflexxes::MotorAngleList& newAnglesOfMotors, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompReflexxes__Reflexxes__setJointPosition_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompReflexxes::Reflexxes* __del = dynamic_cast< ::IceDelegate::RoboCompReflexxes::Reflexxes*>(__delBase.get());
            __del->setJointPosition(newAnglesOfMotors, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompReflexxes::Reflexxes::begin_setJointPosition(const ::RoboCompReflexxes::MotorAngleList& newAnglesOfMotors, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompReflexxes__Reflexxes__setJointPosition_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompReflexxes__Reflexxes__setJointPosition_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(newAnglesOfMotors);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompReflexxes::Reflexxes::end_setJointPosition(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __RoboCompReflexxes__Reflexxes__setJointPosition_name);
}

bool
IceProxy::RoboCompReflexxes::Reflexxes::getStatePosition(const ::RoboCompReflexxes::MotorAngleList& anglesOfMotors, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompReflexxes__Reflexxes__getStatePosition_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__RoboCompReflexxes__Reflexxes__getStatePosition_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompReflexxes::Reflexxes* __del = dynamic_cast< ::IceDelegate::RoboCompReflexxes::Reflexxes*>(__delBase.get());
            return __del->getStatePosition(anglesOfMotors, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompReflexxes::Reflexxes::begin_getStatePosition(const ::RoboCompReflexxes::MotorAngleList& anglesOfMotors, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompReflexxes__Reflexxes__getStatePosition_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompReflexxes__Reflexxes__getStatePosition_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompReflexxes__Reflexxes__getStatePosition_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(anglesOfMotors);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

bool
IceProxy::RoboCompReflexxes::Reflexxes::end_getStatePosition(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompReflexxes__Reflexxes__getStatePosition_name);
    bool __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

const ::std::string&
IceProxy::RoboCompReflexxes::Reflexxes::ice_staticId()
{
    return ::RoboCompReflexxes::Reflexxes::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::RoboCompReflexxes::Reflexxes::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::RoboCompReflexxes::Reflexxes);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::RoboCompReflexxes::Reflexxes::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::RoboCompReflexxes::Reflexxes);
}

::IceProxy::Ice::Object*
IceProxy::RoboCompReflexxes::Reflexxes::__newInstance() const
{
    return new Reflexxes;
}

void
IceDelegateM::RoboCompReflexxes::Reflexxes::setJointPosition(const ::RoboCompReflexxes::MotorAngleList& newAnglesOfMotors, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompReflexxes__Reflexxes__setJointPosition_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(newAnglesOfMotors);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

bool
IceDelegateM::RoboCompReflexxes::Reflexxes::getStatePosition(const ::RoboCompReflexxes::MotorAngleList& anglesOfMotors, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompReflexxes__Reflexxes__getStatePosition_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(anglesOfMotors);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    bool __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

void
IceDelegateD::RoboCompReflexxes::Reflexxes::setJointPosition(const ::RoboCompReflexxes::MotorAngleList& newAnglesOfMotors, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::RoboCompReflexxes::MotorAngleList& __p_newAnglesOfMotors, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_newAnglesOfMotors(__p_newAnglesOfMotors)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompReflexxes::Reflexxes* servant = dynamic_cast< ::RoboCompReflexxes::Reflexxes*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->setJointPosition(_m_newAnglesOfMotors, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::RoboCompReflexxes::MotorAngleList& _m_newAnglesOfMotors;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompReflexxes__Reflexxes__setJointPosition_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(newAnglesOfMotors, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

bool
IceDelegateD::RoboCompReflexxes::Reflexxes::getStatePosition(const ::RoboCompReflexxes::MotorAngleList& anglesOfMotors, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(bool& __result, const ::RoboCompReflexxes::MotorAngleList& __p_anglesOfMotors, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_anglesOfMotors(__p_anglesOfMotors)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompReflexxes::Reflexxes* servant = dynamic_cast< ::RoboCompReflexxes::Reflexxes*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->getStatePosition(_m_anglesOfMotors, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        bool& _result;
        const ::RoboCompReflexxes::MotorAngleList& _m_anglesOfMotors;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompReflexxes__Reflexxes__getStatePosition_name, ::Ice::Normal, __context);
    bool __result;
    try
    {
        _DirectI __direct(__result, anglesOfMotors, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::Ice::Object* RoboCompReflexxes::upCast(::RoboCompReflexxes::Reflexxes* p) { return p; }

namespace
{
const ::std::string __RoboCompReflexxes__Reflexxes_ids[2] =
{
    "::Ice::Object",
    "::RoboCompReflexxes::Reflexxes"
};

}

bool
RoboCompReflexxes::Reflexxes::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__RoboCompReflexxes__Reflexxes_ids, __RoboCompReflexxes__Reflexxes_ids + 2, _s);
}

::std::vector< ::std::string>
RoboCompReflexxes::Reflexxes::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__RoboCompReflexxes__Reflexxes_ids[0], &__RoboCompReflexxes__Reflexxes_ids[2]);
}

const ::std::string&
RoboCompReflexxes::Reflexxes::ice_id(const ::Ice::Current&) const
{
    return __RoboCompReflexxes__Reflexxes_ids[1];
}

const ::std::string&
RoboCompReflexxes::Reflexxes::ice_staticId()
{
    return __RoboCompReflexxes__Reflexxes_ids[1];
}

::Ice::DispatchStatus
RoboCompReflexxes::Reflexxes::___setJointPosition(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::RoboCompReflexxes::MotorAngleList newAnglesOfMotors;
    __is->read(newAnglesOfMotors);
    __inS.endReadParams();
    setJointPosition(newAnglesOfMotors, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RoboCompReflexxes::Reflexxes::___getStatePosition(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::RoboCompReflexxes::MotorAngleList anglesOfMotors;
    __is->read(anglesOfMotors);
    __inS.endReadParams();
    bool __ret = getStatePosition(anglesOfMotors, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __RoboCompReflexxes__Reflexxes_all[] =
{
    "getStatePosition",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "setJointPosition"
};

}

::Ice::DispatchStatus
RoboCompReflexxes::Reflexxes::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__RoboCompReflexxes__Reflexxes_all, __RoboCompReflexxes__Reflexxes_all + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __RoboCompReflexxes__Reflexxes_all)
    {
        case 0:
        {
            return ___getStatePosition(in, current);
        }
        case 1:
        {
            return ___ice_id(in, current);
        }
        case 2:
        {
            return ___ice_ids(in, current);
        }
        case 3:
        {
            return ___ice_isA(in, current);
        }
        case 4:
        {
            return ___ice_ping(in, current);
        }
        case 5:
        {
            return ___setJointPosition(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
RoboCompReflexxes::Reflexxes::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
RoboCompReflexxes::Reflexxes::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
RoboCompReflexxes::__patch(ReflexxesPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompReflexxes::ReflexxesPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompReflexxes::Reflexxes::ice_staticId(), v);
    }
}
